version: '3.4'

services:
  client:
    image: lab03_client
    build:
      context: ./client/
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001
    networks:
      - lab03
  exchange:
    image: lab03_exchange
    build:
      context: ./exchange/
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    networks:
      - lab03
  db:
    image: postgres:15.2-alpine
    env_file:
      - ./.env
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - lab03

volumes:
  postgres_data:

networks:
  lab03:
